name: deploy
on:
  push:
    branches:
      - main

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  dev-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ admin, user ]
        include:
          - target: admin
            MODULE: admin
          - target: user
            MODULE: user

    steps:
      - uses: actions/checkout@v4

      # 공통 변수 + matrix 기반 변수 설정
      - name: set env
        id: set-envs
        run: |
          PROFILE=dev
          MODULE=${{ matrix.MODULE }}
          APPLICATION_NAME=kt-techup-1
          API_ZIP=$APPLICATION_NAME-$MODULE-$PROFILE-$(date +'%Y%m%dT%H%M%S%Z').zip
          ORIGINAL_ZIP_NAME=shopping-$MODULE.zip
          DIR=$MODULE/build/distributions

          echo "PROFILE=$PROFILE" >> $GITHUB_ENV
          echo "MODULE=$MODULE" >> $GITHUB_ENV
          echo "APPLICATION_NAME=$APPLICATION_NAME" >> $GITHUB_ENV
          echo "API_ZIP=$API_ZIP" >> $GITHUB_ENV
          echo "ORIGINAL_ZIP_NAME=$ORIGINAL_ZIP_NAME" >> $GITHUB_ENV
          echo "DIR=$DIR" >> $GITHUB_ENV

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Start Mysql Service
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE shoppingtest;' -uroot -proot

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5

      - name: Run ${{ matrix.target }} Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: ${{ matrix.MODULE }}:zip -x test

      - name: Move ${{ matrix.target }} Api ZIP
        run: |
          mv ${{ env.DIR }}/${{ env.ORIGINAL_ZIP_NAME }} ${{ env.DIR }}/${{ env.API_ZIP }}

      - name: ${{ matrix.target }} deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.BACK_END_DEPLOYER_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.BACK_END_DEPLOYER_SECRET_KEY }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.APPLICATION_NAME }}-${{ env.MODULE }}-env
          version_label: ${{ env.API_ZIP }}
          region: ap-northeast-2
          deployment_package: ${{ env.DIR }}/${{ env.API_ZIP }}

      - name: send slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: GitHub Actions (${{ matrix.target }})
          fields: repo,commit,author,ref,workflow,job,took
        if: always()